//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICADO
    {
        public int ID_CERT { get; set; }
        public int PTS_MIN { get; set; }
        public int PTS_MAX { get; set; }
        public decimal DESCUENTO { get; set; }
        public int TOPE { get; set; }
        public string RUBRO { get; set; }
        public int CONSUMIDOR_ID_CONS { get; set; }
    
        public virtual CONSUMIDOR CONSUMIDOR { get; set; }
    }
}
