//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICADO_EMITIDO
    {
        public int ID_CEMITIDO { get; set; }
        public decimal DESCUENTO { get; set; }
        public int PTS_USADOS { get; set; }
        public string CONSUMIDOR_USERNAME { get; set; }
        public string CONSUMIDOR_RUN { get; set; }
        public int CERTIFICADO_ID_CERT { get; set; }
    
        public virtual CERTIFICADO CERTIFICADO { get; set; }
        public virtual CONSUMIDOR CONSUMIDOR { get; set; }
    }
}
