//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_OFERTA
    {
        public int ID_DET { get; set; }
        public byte[] IMG_BOLETA { get; set; }
        public System.DateTime FEC_VALORACION { get; set; }
        public decimal VALORACION { get; set; }
        public int OFERTA_ID_OFERTA { get; set; }
        public string CONSUMIDOR_USERNAME { get; set; }
        public string CONSUMIDOR_RUN { get; set; }
    
        public virtual CONSUMIDOR CONSUMIDOR { get; set; }
        public virtual OFERTA OFERTA { get; set; }
    }
}
