//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTE
    {
        public int ID_LOTE { get; set; }
        public short CANTIDAD { get; set; }
        public System.DateTime FECHA_LIMITE { get; set; }
        public long PRODUCTO_ID_PROD { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
