//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MisOfertasEntities : DbContext
    {
        public MisOfertasEntities()
            : base("name=MisOfertasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CERTIFICADO> CERTIFICADO { get; set; }
        public DbSet<CONSUMIDOR> CONSUMIDOR { get; set; }
        public DbSet<DETALLE_OFERTA> DETALLE_OFERTA { get; set; }
        public DbSet<DETALLE_PRODUCTO> DETALLE_PRODUCTO { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<LOTE> LOTE { get; set; }
        public DbSet<MENSAJERIA> MENSAJERIA { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PERSONA> PERSONA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<REG_ERROR> REG_ERROR { get; set; }
        public DbSet<REG_PRODUCTO> REG_PRODUCTO { get; set; }
        public DbSet<SUCURSAL> SUCURSAL { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
