//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTA
    {
        public OFERTA()
        {
            this.DETALLE_OFERTA = new HashSet<DETALLE_OFERTA>();
            this.MENSAJERIA = new HashSet<MENSAJERIA>();
        }
    
        public int ID_OFERTA { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FEC_INICIO { get; set; }
        public System.DateTime FEC_TERMINO { get; set; }
        public byte[] IMG_OFERTA { get; set; }
        public decimal VALORACION_TOTAL { get; set; }
        public decimal PORC_DESC { get; set; }
        public int SUCURSAL_ID_SUCUR { get; set; }
        public long PRODUCTO_ID_PROD { get; set; }
    
        public virtual ICollection<DETALLE_OFERTA> DETALLE_OFERTA { get; set; }
        public virtual ICollection<MENSAJERIA> MENSAJERIA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
