//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.CONSUMIDOR = new HashSet<CONSUMIDOR>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
        }
    
        public string RUN { get; set; }
        public string NOMBRE { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string SEXO { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime FEC_NAC { get; set; }
    
        public virtual ICollection<CONSUMIDOR> CONSUMIDOR { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
    }
}
